#!/bin/bash
# luckpool = stratum+tcp://ap.luckpool.net:3956
# vipor    = stratum+tcp://cn.vipor.net:5040
# Path to ccminer executable
ccminer_path="/path/to/ccminer"

# Mining parameters
algorithm="verus"
stratum_server="stratum+tcp://ap.luckpool.net:3956"
base_username="RQDmLkZbRKs51qVnKcPHQeDtPcBZ2Favvk"
#hostname=$(hostname)
hostname=VERUS_MINER
username="${base_username}.${hostname}"
extra_params="xnsub"
threads=4

# Log file path
log_file="/var/log/ccminer.log"


# Run ccminer with specified parameters and append output to log file
./ccminer -a "$algorithm" -o "$stratum_server" -u "$username" -p "$extra_params" -t "$threads" | tee -a "$log_file"
