#!/bin/bash

# auto update on boot
cd ~/etc/systemd/system/
curl -o apt-update.service -k https://raw.githubusercontent.com/lunacomp/ccminer-lunacomp/main/apt-update.service
sudo systemctl daemon-reload
sudo systemctl enable apt-update.service


# Navigate to the ccminer directory
cd ~/ccminer

# Clean old configuration
rm -f config.json > /dev/null
rm -f start.sh > /dev/null
rm -f mining.sh > /dev/null

# Disable xmrig
sudo systemctl stop xmrig > /dev/null
sudo systemctl disable xmrig > /dev/null


# Download the run.sh script and make it executable
wget -O run.sh https://raw.githubusercontent.com/lunacomp/ccminer-lunacomp/main/config-solo
chmod +x run.sh

# Go back to the home directory
cd ~

# Download the start.sh script and make it executable
curl -o start.sh -k https://raw.githubusercontent.com/lunacomp/ccminer-lunacomp/main/start.sh
chmod +x start.sh

# Add start.sh to cron jobs for execution at reboot
echo "@reboot bash /root/start.sh &" | sudo crontab -

# Remove any existing ccminer service
sudo rm -f /etc/systemd/system/ccminer.service

# Kill any running ccminer processes
sudo killall ccminer

# Start ccminer
./start.sh &
